version: '20.10.17'

services:
  dash-app:
    build:
      context: ./dash-app
      dockerfile: Dockerfile
    container_name: dash-app
    ports:
      - 80:80
    depends_on:
      - backend
      
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    container_name: backend
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/ebankdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW-SQL=false
          
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ebankdb
    container_name: postgresqldb
    


  
    
 